language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-modules.txt
  - pip install coveralls
script: make travis
after_success: coveralls
notifications:
  email:
    - silpa-discuss@nongnu.org
  irc:
    channels:
      - "irc.freenode.net#silpa"
    on_success: change
    on_failure: change
    use_notice: true